name: Lint ARM Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ARM TTK
        shell: pwsh
        run: |
          $installPath = "$env:USERPROFILE\arm-ttk"
          New-Item -ItemType Directory -Path $installPath -Force
          Invoke-WebRequest -Uri "https://github.com/Azure/arm-ttk/archive/refs/heads/master.zip" -OutFile "$installPath\arm-ttk.zip"
          Expand-Archive -Path "$installPath\arm-ttk.zip" -DestinationPath $installPath -Force
          $ttkPath = (Get-ChildItem -Path $installPath -Filter "arm-ttk-master" -Directory).FullName
          Copy-Item -Path "$ttkPath\arm-ttk.psd1" -Destination $installPath -Force
          Copy-Item -Path "$ttkPath\arm-ttk.psm1" -Destination $installPath -Force
          Copy-Item -Path "$ttkPath\testcases" -Destination $installPath -Recurse -Force
          $env:PSModulePath = $env:PSModulePath + ";$installPath"

      - name: Run ARM TTK Tests
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:USERPROFILE\arm-ttk"
          Import-Module "$env:USERPROFILE\arm-ttk\arm-ttk.psd1" -Verbose
          Test-AzTemplate -TemplatePath "$env:GITHUB_WORKSPACE\azuredeploy.json"
