name: Lint ARM Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest  # Changed to windows-latest since arm-ttk is PowerShell based

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Install ARM TTK
        shell: pwsh
        run: |
          $installPath = "$env:USERPROFILE\arm-ttk"
          New-Item -ItemType Directory -Path $installPath -Force
          Invoke-WebRequest -Uri "https://github.com/Azure/arm-ttk/archive/refs/heads/master.zip" -OutFile "$installPath\arm-ttk.zip"
          Expand-Archive -Path "$installPath\arm-ttk.zip" -DestinationPath $installPath -Force
          $ttkPath = (Get-ChildItem -Path $installPath -Filter "arm-ttk-master" -Directory).FullName
          Copy-Item -Path "$ttkPath\*" -Destination $installPath -Recurse -Force
          echo "$installPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run ARM TTK Tests
        shell: pwsh
        run: |
          Import-Module "$env:USERPROFILE\arm-ttk\arm-ttk.psd1"
          Test-AzTemplate -TemplatePath "$env:GITHUB_WORKSPACE\azuredeploy.json"
